# ----
# Site
source                   : ".tmp/src"
destination              : ".tmp/dist"

title: "IT Solver"
url: "https://www.itsolver.net"
baseurl:
environment: "production"
repository: "https://github.com/itsolver/msp-marketing-site"
timezone: "Australia/Brisbane"
google_analytics_key: "UA-90161029-1"
disqus_shortname:
icon_ready: true
twitter:
  username: "itsolver"
future: false # Publish on schedule future dated posts https://stackoverflow.com/a/5013966

# Default Calendly Booking URL
booking_url: "https://calendly.com/itsolver/on-demand-support"

# Let search engines discover this site quicker
google_site_verification : ""
bing_site_verification   : ""
alexa_site_verification  : ""
yandex_site_verification : "6636a05957c32947"

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: "/the_favicon/android-chrome-192x192.png"
description: "Brisbane and Redland City computer services for small home and business. IT Solver helps you get the best value from your technology investment. We setup and support migrations to the cloud with Google Workspace or Office 365. Repairs and maintenance to keep your home and business equipment online."
author:
  picture: "/assets/images/staff-angus.jpg"
  twitter: "gusmacca"
social:
  name: "IT Solver"
  links:
    - "https://www.itsolver.net/blog/"
    - "https://www.twitter.com/itsolvernet"
    - "https://plus.google.com/105525146496759832582"
    - "https://www.yelp.com.au/biz/it-solver-redland-bay"
    - "https://foursquare.com/v/it-solver/5a65800a0a08ab7fafc50d49"
    - "https://github.com/itsolver/msp-marketing-site"

defaults:
  - scope:
      path: ""
    values:
      image: "/the_favicon/android-chrome-192x192.png"

# -----
# Build

permalink: "pretty"
defaults:
  - scope:
      path: ""
    values:
      header_class: "plain"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "site-audit/**/*.html"
    values:
      sitemap: false

collections:
  case_studies:
    output: false
    permalink: /case-studies/:name/
  skus:
    output: true
    permalink: /:name/
  categories:
    output: true
    permalink: /:name/

exclude:
- .asset-cache
- .bundle
- .jekyll-cache/
- .jekyll-assets-cache
- .sass-cache
- "*.sublime-project"
- "*.sublime-workspace"
- Capfile
- config
- Gemfile
- Gemfile.lock
- Gruntfile.js
- gulpfile.js
- log
- node_modules
- package.json
- Rakefile
- README
- tmp
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
